In [1]:
import numpy as np

temperatures = np.array([30, 32, 29, 35, 31])
print(temperatures.shape)
print(temperatures.size)
print(temperatures.ndim)
print(temperatures.dtype)

(5,)
5
1
int64


In [5]:
print(np.zeros((4, 4)))
print(np.ones((5, 5)))
print(np.full((3, 3), 9))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
